language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
  - pip install -e .
  - pip install -e .[test]

script:
  - python -m zenroom install --user
  - nosetests

after_success:
  - coveralls
