language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

before_install:
  - ./.before_install
  - export ZENROOM_BIN=/home/travis/zenroom_binary/src/zenroom_shared

install:
  - pip install -e .
  - pip install -e .[test]

script:
  - nosetests

after_success:
  - coveralls